#define	AUSAS		0
#define	AUTO_LOCKING	0
#define	BITS_UCHAR	8
#define	BITS_UINT	32
#define	BITS_ULLONG	64
#define	BITS_ULONG	64
#define	BITS_USHORT	16
#define	BITS_Usize_t	64
#define	BITS_Ussize_t	64
#define	BITS_Utime_t	64
#define	BSD4		0
#define	BSD4V		'0'
#define	CARR_ON_BUG	1
#define	CHECK_LICENCE	1
#define	FCNTL		1
#define	FILEBUFFERSIZE	8192
#define	FLOCK		0
#define	KILL_0		1
#define	LOCKF		1
#define	MAXRETSIZE	10000
#define	MAX_CHAR	0x7f 
#define	MAX_INT	0x7fffffff 
#define	MAX_LLONG	(Llong)0x7fffffffffffffffLL
#define	MAX_LONG	0x7fffffffffffffffL
#define	MAX_SHORT	0x7fff 
#define	MAX_UCHAR	(Uchar)0xff 
#define	MAX_UINT	(Uint)0xffffffff 
#define	MAX_ULLONG	(Ullong)0xffffffffffffffffLL
#define	MAX_ULONG	(Ulong)0xffffffffffffffffL
#define	MAX_USHORT	(Ushort)0xffff 
#define	MAX_Usize_t	(size_t)0xffffffffffffffffL
#define	MAX_Ussize_t	(ssize_t)0xffffffffffffffffL
#define	MAX_Utime_t	(time_t)0xffffffffffffffffL
#define	MAX_size_t	(size_t)0x7fffffffffffffffL
#define	MAX_ssize_t	(ssize_t)0x7fffffffffffffffL
#define	MAX_time_t	(time_t)0x7fffffffffffffffL
#define	MINSLEEP	1
#define	NDIRLIB		2
#define	NEED_BCOPY	0
#define	NVETIMEDELAY	600
#define	PGRP		1
#define	PIPE_FSTAT_SIZE	0
#define	PRINTF_NULLS	1
#define	PROTO_STATS	1
#define	RENAME_2	1
#define	SPRF_SIZE	1
#define	SUN3		1
#define	SYSTEM		5
#define	SYSVREL		3
#define	SYS_LOCKING	0
#define	TCP_IP		1
#define	UDP_IP		1
#define	V8		0
#define	VCDAEMON_STATS	1
#define	VPRINTF		1
#define	WAIT_RESTART	1
#define	X25		0
